/**
 * Data entry demo: Create a CSV report, open in Notepad, type structured data.
 * Simulates filling out a form-like document with multiple fields.
 *
 * Run: node examples/windows/data-entry.mjs
 */
import { createComputerUseServer } from '../../dist/server.js'
import { connectInProcess } from '../../dist/client.js'
import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'

const outDir = path.join(os.tmpdir(), 'cu-dataentry')
fs.mkdirSync(outDir, { recursive: true })

/** List only Notepad windows, tolerant of the v7 { windows: [...] } shape. */
async function notepadWindows(client) {
  const raw = JSON.parse((await client.listWindows()).content[0].text)
  const arr = Array.isArray(raw) ? raw : (raw.windows ?? [])
  return arr.filter(w => w.bundleId?.toLowerCase().includes('notepad'))
}

/** Open a fresh Notepad scratch tab (Ctrl+N) without touching existing tabs. */
async function openScratchTab(client) {
  const existing = await notepadWindows(client)
  if (existing.length > 0) {
    const winId = existing[0].windowId
    await client.activateWindow(winId)
    await client.wait(0.3)
    await client.key('ctrl+n', undefined, { targetWindowId: winId, focusStrategy: 'strict' })
    await client.wait(0.6)
    return winId
  }
  await client.callTool('run_script', { language: 'powershell', script: 'Start-Process notepad' })
  await client.wait(2)
  return (await notepadWindows(client))[0]?.windowId
}

/** Save the current tab via the Save As dialog using accessibility. */
async function saveViaDialog(client, winId, savePath) {
  await client.key('ctrl+s', undefined, { targetWindowId: winId, focusStrategy: 'strict' })
  await client.wait(1.2)
  await client.setValue(winId, 'AXTextField', 'File name:', savePath)
  await client.wait(0.4)
  await client.pressButton(winId, 'Save')
  await client.wait(1.2)
  await client.pressButton(winId, 'Yes') // confirm overwrite if prompted (no-op otherwise)
  await client.wait(0.5)
}

async function main() {
  const server = createComputerUseServer()
  const client = await connectInProcess(server)
  console.log(`+ ${(await client.listTools()).length} tools\n`)

  // Sample data to enter
  const employees = [
    { name: 'Alice Johnson', dept: 'Engineering', role: 'Senior Developer', salary: '125000' },
    { name: 'Bob Smith', dept: 'Marketing', role: 'Campaign Manager', salary: '95000' },
    { name: 'Carol Williams', dept: 'Finance', role: 'Financial Analyst', salary: '110000' },
    { name: 'David Brown', dept: 'Engineering', role: 'DevOps Lead', salary: '130000' },
    { name: 'Eve Davis', dept: 'HR', role: 'Recruiter', salary: '85000' },
  ]

  // Step 1: Open a fresh Notepad scratch tab
  console.log('1. Opening a fresh Notepad tab...')
  const winId = await openScratchTab(client)
  if (!winId) { console.log('   Notepad window not found'); await client.close(); return }
  const opts = { targetWindowId: winId, focusStrategy: 'strict' }

  // Step 2: Build the whole report as one string. Typing it in a single call
  // routes long/multi-line text through the clipboard internally, which is
  // reliable and preserves line breaks (rapid back-to-back type calls can
  // race the clipboard).
  console.log('2. Building report...')
  const totalSalary = employees.reduce((sum, e) => sum + parseInt(e.salary), 0)
  const doc =
    'Employee Report - Generated by computer-use-mcp\n' +
    'Date: ' + new Date().toLocaleDateString() + '\n' +
    '='.repeat(60) + '\n\n' +
    'Name,Department,Role,Salary\n' +
    '-'.repeat(60) + '\n' +
    employees.map(e => `${e.name},${e.dept},${e.role},$${e.salary}`).join('\n') + '\n' +
    '\n' + '-'.repeat(60) + '\n' +
    `Total employees: ${employees.length}\n` +
    `Total salary: $${totalSalary.toLocaleString()}\n` +
    `Average salary: $${Math.round(totalSalary / employees.length).toLocaleString()}\n`

  // Step 3: Type the report in one call (targeted at our tab)
  console.log('3. Entering employee data...')
  await client.type(doc, undefined, opts)
  await client.wait(0.5)

  // Step 5: Screenshot the completed report
  console.log('4. Screenshot...')
  const shot = await client.screenshot({ width: 800 })
  const img = shot.content.find(c => c.type === 'image')
  if (img) {
    fs.writeFileSync(path.join(outDir, 'report.jpg'), Buffer.from(img.data, 'base64'))
    console.log('   saved: report.jpg')
  }

  // Step 6: Save the file via the Save As dialog (accessibility-driven)
  console.log('5. Saving report...')
  const savePath = path.join(outDir, 'employee-report.csv')
  await saveViaDialog(client, winId, savePath)

  // Step 7: Close only our tab (preserves any other tabs)
  await client.key('ctrl+w', undefined, opts)
  await client.wait(0.5)

  // Step 8: Verify the saved file
  console.log('6. Verifying saved file...')
  const content = await client.callTool('filesystem', { mode: 'read', path: savePath })
  const lines = content.content[0]?.text?.split('\n').filter(l => l.trim()) || []
  console.log(`   Lines: ${lines.length}`)
  console.log(`   First: ${lines[0]}`)
  console.log(`   Last:  ${lines[lines.length - 1]}`)

  await client.close()
  console.log(`\n+ Done -- check ${outDir}`)
}

main().catch(e => { console.error(e); process.exit(1) })
