/**
 * Data entry demo: Create a CSV report, open in Notepad, type structured data.
 * Simulates filling out a form-like document with multiple fields.
 *
 * Run: node examples/windows/data-entry.mjs
 */
import { createComputerUseServer } from '../../dist/server.js'
import { connectInProcess } from '../../dist/client.js'
import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'

const outDir = path.join(os.tmpdir(), 'cu-dataentry')
fs.mkdirSync(outDir, { recursive: true })

async function main() {
  const server = createComputerUseServer()
  const client = await connectInProcess(server)
  console.log(`+ ${(await client.listTools()).length} tools\n`)

  // Sample data to enter
  const employees = [
    { name: 'Alice Johnson', dept: 'Engineering', role: 'Senior Developer', salary: '125000' },
    { name: 'Bob Smith', dept: 'Marketing', role: 'Campaign Manager', salary: '95000' },
    { name: 'Carol Williams', dept: 'Finance', role: 'Financial Analyst', salary: '110000' },
    { name: 'David Brown', dept: 'Engineering', role: 'DevOps Lead', salary: '130000' },
    { name: 'Eve Davis', dept: 'HR', role: 'Recruiter', salary: '85000' },
  ]

  // Step 1: Open Notepad
  console.log('1. Opening Notepad...')
  await client.callTool('run_script', { language: 'powershell', script: 'Start-Process notepad' })
  await client.wait(2)

  // Step 2: Type the header
  console.log('2. Typing CSV header...')
  await client.type('Employee Report - Generated by computer-use-mcp\n')
  await client.type('Date: ' + new Date().toLocaleDateString() + '\n')
  await client.type('=' .repeat(60) + '\n\n')
  await client.type('Name,Department,Role,Salary\n')
  await client.type('-'.repeat(60) + '\n')

  // Step 3: Enter each employee record
  console.log('3. Entering employee data...')
  for (const emp of employees) {
    await client.type(`${emp.name},${emp.dept},${emp.role},$${emp.salary}\n`)
    await client.wait(0.1)
    console.log(`   + ${emp.name}`)
  }

  // Step 4: Add summary
  await client.type('\n' + '-'.repeat(60) + '\n')
  const totalSalary = employees.reduce((sum, e) => sum + parseInt(e.salary), 0)
  await client.type(`Total employees: ${employees.length}\n`)
  await client.type(`Total salary: $${totalSalary.toLocaleString()}\n`)
  await client.type(`Average salary: $${Math.round(totalSalary / employees.length).toLocaleString()}\n`)
  await client.wait(0.5)

  // Step 5: Screenshot the completed report
  console.log('4. Screenshot...')
  const shot = await client.screenshot({ width: 800 })
  const img = shot.content.find(c => c.type === 'image')
  if (img) {
    fs.writeFileSync(path.join(outDir, 'report.jpg'), Buffer.from(img.data, 'base64'))
    console.log('   saved: report.jpg')
  }

  // Step 6: Save the file
  console.log('5. Saving report...')
  const savePath = path.join(outDir, 'employee-report.csv')
  await client.key('ctrl+s')
  await client.wait(1)
  await client.type(savePath, undefined, { focusStrategy: 'none' })
  await client.key('return')
  await client.wait(1)
  await client.key('return') // replace dialog
  await client.wait(0.5)

  // Step 7: Close Notepad
  await client.key('alt+f4')
  await client.wait(0.5)

  // Step 8: Verify the saved file
  console.log('6. Verifying saved file...')
  const content = await client.callTool('filesystem', { mode: 'read', path: savePath })
  const lines = content.content[0]?.text?.split('\n').filter(l => l.trim()) || []
  console.log(`   Lines: ${lines.length}`)
  console.log(`   First: ${lines[0]}`)
  console.log(`   Last:  ${lines[lines.length - 1]}`)

  await client.close()
  console.log(`\n+ Done -- check ${outDir}`)
}

main().catch(e => { console.error(e); process.exit(1) })
