export function officePlatformInstructions(platform = process.platform) {
  if (platform === 'win32') return `Use run_script with PowerShell and the installed Office COM interfaces, one bounded script per app. Create only new Workbooks/Documents/Presentations; retain references to your own objects, save in Open XML formats and close only those objects in finally. Never call application Quit on a shared Office instance or change global security/alert settings. Use formulas and explicit USD number formats in Excel; calculate and read back totals, and create a revenue/profit chart before saving. Create exactly three PowerPoint slides. Use discovered running process targets for screenshots; Start-menu launch IDs are not process names.`
  if (platform === 'darwin') return `Use one compact AppleScript run per app using the tested patterns below; do not load an application dictionary. Use the returned targetApp bundle IDs, create a new document/workbook/presentation, and save to the exact output paths. In Excel, assign worksheet 1 of fixture to a variable before writing ranges, use formulas (not hard-coded totals), create the chart before saving, and set explicit USD number formats so locale does not change the currency. In PowerPoint, create slide 1 with "make new slide at end of fixture", then add exactly two more slides and set their text. In Word, set the new document's text before saving. Office Save As may invalidate old document references; reacquire the saved document by its full saved path before reading or closing it.`
  throw new Error('The Microsoft Office showcase requires desktop Office on macOS or Windows. On Linux, use the inspect or paint showcase; this recipe does not implement LibreOffice automation.')
}

export const RECIPES = {
  paint: {
    title: 'Van Gogh-inspired painter',
    tools: ['discover_applications','get_app_capabilities','get_tool_guide','open_application','list_windows','get_window','get_display_size','list_displays','screenshot','get_ui_tree','find_element','click_element','set_value','select_menu_item','list_menu_bar','activate_window','key','type','left_click','left_click_drag','openai_computer','wait'],
    task: ({ output, app, studio }) => `Create an original Van Gogh-inspired nocturnal landscape: a cobalt and ultramarine sky, sweeping luminous swirls, golden stars and moon, a dark cypress silhouette, rolling hills and a small village. Use visible, varied brush strokes and a deliberate composition. Aim for a finished, expressive painting rather than a few demonstration lines.
${studio ? `The host opened a fresh paint studio window titled "MCP Paint Studio". Use paint_strokes to batch model-designed brush paths in canvas coordinates (1000 by 600). This helper sets the palette and brush using real MCP input, then paints your paths; it does not generate any artwork. Build roughly 80-150 varied strokes over 8-15 layers. Use thick strokes for backgrounds and narrow, varied strokes for texture and luminous swirls. The helper returns a fresh screenshot. Finish with finish_painting to click Export PNG and verify the saved artifact. The host saves the export into ${output}.` : `Discover ${app ?? 'a suitable installed paint program such as Paintbrush, Krita, Pinta or Paint'} by name, open it, and create a NEW canvas. Save the painting as painting.png in ${output}. Do not install an application or overwrite an existing document.`}
Observe the window before drawing and between major layers. Use openai_computer drag actions with full point paths for curved brush strokes. Group a modest number of strokes per call to reduce model round trips; inspect results after each layer. Revalidate window geometry before converting image coordinates to logical desktop pixels. Use only GUI painting: do not generate an image with code, import a finished image, or draw through browser JavaScript. End with a final screenshot and verify the export. Describe the actual result and any incomplete details.`
  },
  office: {
    title: 'Office report producer',
    tools: ['discover_applications','get_app_capabilities','get_tool_guide','run_script','list_windows','get_window','get_ui_tree','find_element','screenshot','open_application','wait'],
    task: ({output, platform}) => `Use application discovery to find Microsoft Excel, Word and PowerPoint. Produce a coordinated quarterly business review using the apps' scripting interfaces, with accessibility as an observation fallback. Create only NEW documents. Save quarterly-review.xlsx, quarterly-review.docx and quarterly-review.pptx in ${output}.
Dataset (USD): North revenue 120000 costs 78000; South revenue 95000 costs 66500; East revenue 142000 costs 92300; West revenue 108000 costs 73440.
Excel: a readable table, formulas for profit and margin, totals and a revenue/profit chart. Independently read back the computed total revenue (465000) and profit (154760).
Word: a concise executive memo with a summary, regional findings and three recommendations grounded in the supplied data.
PowerPoint: a polished three-slide briefing: headline results, regional comparison, and recommendations. Keep the figures consistent across apps. Use screenshots to review the open documents, save each one, and close only documents you created.
${officePlatformInstructions(platform)} Close only the documents you created, using their full saved paths when available. Avoid repeated screenshots or exploratory calls; one final screenshot per app is enough for a visual sanity check. Report missing apps or unsupported operations explicitly; do not claim success just because a script returned.`
  },
  inspect: {
    title: 'Desktop capability inspector',
    tools: ['discover_applications','get_app_capabilities','get_tool_guide','list_running_apps','list_windows','get_display_size','list_displays'],
    task: () => 'Discover installed Office and creative apps, identify which are running, and explain the best automation route for each using tool evidence. Return a short capability report with scripting support, accessibility limitations and stable targeting IDs. Do not launch apps, read document contents, capture screenshots, or change desktop state.'
  },
}
