/** Self-contained MCP App: no network, telemetry, remote assets or HTML interpolation of observations. */
export const SESSION_CONSOLE_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font:14px system-ui}body{margin:0;padding:20px;max-width:760px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h1{font-size:19px}button{padding:9px 14px;border-radius:7px;border:1px solid #888;cursor:pointer}#stop{background:#a22;color:white}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:220px;overflow:auto}#controls{display:grid;gap:6px}#state{font-weight:600}small{display:block;margin:12px 0;opacity:.8}</style></head><body>
<header><h1>Desktop session</h1><button id="stop" disabled>Pause for takeover</button></header><p id="state" role="status" aria-live="polite">Connecting to host…</p><small>Pause stops queued work for this session. Resume through your trusted host after reviewing the desktop.</small><h2>Observed controls</h2><div id="controls"></div><h2>Last operation</h2><pre id="last">No operation yet.</pre><button id="refresh" disabled>Refresh status</button>
<script>
let sequence=0,sessionId,hostOrigin,ready=false;const pending=new Map();
function send(message){parent.postMessage({jsonrpc:'2.0',...message},hostOrigin&&hostOrigin!=='null'?hostOrigin:'*')}
function rpc(method,params){return new Promise((resolve,reject)=>{const id=++sequence;const timeout=setTimeout(()=>{pending.delete(id);reject(Error('Host did not respond'))},10000);pending.set(id,{resolve,reject,timeout});send({id,method,params})})}
function render(value){if(!value||!value.sessionId)return;sessionId=value.sessionId;document.getElementById('state').textContent=value.state+' · '+sessionId;document.getElementById('last').textContent=JSON.stringify(value.lastOperation||{},null,2);document.getElementById('stop').disabled=!ready||value.state==='paused';document.getElementById('refresh').disabled=!ready;const container=document.getElementById('controls');container.replaceChildren();for(const node of value.observation?.nodes||[]){if(!node.label)continue;const button=document.createElement('button');button.textContent=node.role+': '+node.label;button.onclick=()=>rpc('ui/message',{role:'user',content:[{type:'text',text:'Selected control '+JSON.stringify({sessionId,observationId:value.observation.id,elementId:node.elementId,label:node.label})}]}).catch(showError);container.append(button)}}
function showError(error){document.getElementById('state').textContent=error.message||String(error)}
function valueOf(result){if(result.isError)throw Error(result.content?.[0]?.text||'Operation failed');return result.structuredContent||JSON.parse(result.content?.find(c=>c.type==='text')?.text||'{}')}
async function refresh(){if(sessionId)render(valueOf(await rpc('tools/call',{name:'desktop_console',arguments:{sessionId}})))}
window.addEventListener('message',event=>{if(event.source!==parent||!event.data||event.data.jsonrpc!=='2.0')return;if(hostOrigin&&event.origin!==hostOrigin)return;const message=event.data;if(message.id&&pending.has(message.id)){if(!hostOrigin)hostOrigin=event.origin;const p=pending.get(message.id);pending.delete(message.id);clearTimeout(p.timeout);message.error?p.reject(Error(message.error.message)):p.resolve(message.result)}else if(message.method==='ui/notifications/tool-result'){try{render(valueOf(message.params))}catch(e){showError(e)}}else if(message.method==='ui/resource-teardown'){Promise.resolve(sessionId?rpc('tools/call',{name:'desktop_pause',arguments:{sessionId}}):undefined).finally(()=>send({id:message.id,result:{}}))}});
document.getElementById('stop').onclick=async()=>{try{render(valueOf(await rpc('tools/call',{name:'desktop_pause',arguments:{sessionId}})))}catch(e){showError(e)}};
document.getElementById('refresh').onclick=()=>refresh().catch(showError);
rpc('ui/initialize',{appInfo:{name:'computer-use-session-console',version:'1.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>{ready=true;send({method:'ui/notifications/initialized',params:{}});document.getElementById('state').textContent='Waiting for session';if(sessionId)refresh().catch(showError)}).catch(showError);
</script></body></html>`
